export const teamList = [
    "Athena",
    "Jelly Bob",
    "Fizzle",
    "Blizz",
    "Kripz",
    "Zeri",
    "Profries",
    "Haly Bake",
    "Fragante",
    "K'otton",
    "Day One",
    "Locomto",
    "Let's Plant",
    "GottaGO",
    "Harn",
    "Tagme",
    "R-ROI",
    "Indicat",
    "Yeobo",
    "Frescas",
    "Giadina",
    "CoGrow",
    "Wastic",
];
